import { DataFilter } from "../interfaces/filter";

export let dataFilter: DataFilter = {
    animals: false,
    kids: false,
    garage: false,
    furnished: false,
    barbecue: false,
    swimmingPool: false,
    porch: false,
    garden: false,
    airconditioning: false,
    internet: false,
    security: false,
    bathrooms: null,
    floorImmobile: null,
    vacancyCar: null,
    people: null,
    rooms: null,
    minimumArea: null,
    maximumArea: null,
    minimumValue: null,
    maximumValue: null,
    advertiserName: "",
    immobileType: "",
};
